syntax = "proto3";

package juki.engine.v1;

import "juki/common/v1/common.proto";

option go_package = "juki-engine/pkg/gen/juki/engine/v1";

service ComponentService {
  rpc CreateComponent(CreateComponentRequest) returns (CreateComponentResponse);
  rpc UpdateComponent(UpdateComponentRequest) returns (UpdateComponentResponse);
  rpc DeleteComponent(DeleteComponentRequest) returns (DeleteComponentResponse);
  rpc ListComponents(ListComponentsRequest) returns (ListComponentsResponse);
}

message CreateComponentRequest {
  string project_id = 1;
  string name = 2;
  string content = 3;
}

message CreateComponentResponse {
  UserComponent component = 1;
}

message UpdateComponentRequest {
  string id = 1;
  string name = 2;
  string content = 3;
}

message UpdateComponentResponse {
  UserComponent component = 1;
}

message DeleteComponentRequest {
  string id = 1;
}

message DeleteComponentResponse {
  bool success = 1;
}

message ListComponentsRequest {
  string project_id = 1;
}

message ListComponentsResponse {
  repeated UserComponent components = 1;
}

message UserComponent {
  string id = 1;
  string project_id = 2;
  string name = 3;
  string content = 4; // JSON stringified component
  juki.common.v1.Metadata meta = 5;
}
