syntax = "proto3";

package juki.engine.v1;
option go_package = "juki-engine/pkg/gen/juki/engine/v1";

import "juki/common/v1/common.proto";


message CreatePageRequest {
  string name = 1;
  juki.common.v1.PageType type = 2;
  juki.common.v1.AccessType access = 3;
  string project_id = 4;
}

message CreatePageResponse {
  Page page = 1;
}

message GetPageRequest {
    string id = 1;
}

message GetPageResponse {
    Page page = 1;
}

message GetPagesRequest {}

message GetPagesResponse {
  repeated Page pages = 1;
}

message DeletePageRequest {
  string id = 1;
}

message UpdatePageRequest {
  string id = 1;
  string name = 2;
  string route = 3;
  juki.common.v1.PageType type = 4;
  juki.common.v1.AccessType access = 5;
  string content = 6;
}

message UpdatePageResponse {
    Page page = 1;
}

message SavePageRequest {
    string project_id = 1;
    string page_id = 2;
    string content = 3;
}

message SavePageResponse {
    bool success = 1;
    string message = 2;
}

message Page {
  string id = 1;
  string name = 2;
  string route = 3;
  juki.common.v1.PageType type = 4;
  juki.common.v1.AccessType access = 5;
  string content = 6; // JSON stringified page content
  string project_id = 7;
  string layout_id = 8;
  juki.common.v1.Metadata meta = 9;
  string raw_content = 10;
}
