syntax = "proto3";

package juki.engine.v1;
option go_package = "juki-engine/pkg/gen/juki/engine/v1";

import "juki/common/v1/common.proto";
import "juki/engine/v1/page.proto";
import "juki/engine/v1/component.proto";
import "juki/engine/v1/layout.proto";
import "juki/engine/v1/route.proto";


message Project {
  string id = 1;
  string name = 2;
  string description = 3;
  ProjectSettings settings = 4;
  repeated Page pages = 5;
  repeated Layout layouts = 6;
  repeated UserComponent user_components = 7;
  RouteNode root_route = 8;
  juki.common.v1.Metadata meta = 9;
  int32 port = 10;
  string api_key = 11;
  string path = 12;
  string global_css = 13;
}

message ProjectSettings {
  bool use_typescript = 1;
  string framework = 2; // "NextJS", "Vite", etc.
}

message CreateProjectRequest {
  string name = 1;
  string description = 2;
  string path = 3;
  string framework = 4;
}

message CreateProjectResponse {
  Project project = 1;
}

message GetProjectRequest {
  string id = 1;
}

message GetProjectResponse {
  Project project = 1;
}

message ListProjectsRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListProjectsResponse {
  repeated Project projects = 1;
  int32 total_count = 2;
}

message UpdateProjectRequest {
  Project project = 1;
}

message UpdateProjectResponse {
  Project project = 1;
}

message DeleteProjectRequest {
  string id = 1;
}

message DeleteProjectResponse {
  bool success = 1;
}

message SyncProjectRequest {
    string id = 1;
}

message SyncProjectResponse {
    Project project = 1;
}

message BuildProjectRequest {
    string project_id = 1;
}

message BuildProjectResponse {
    bool success = 1;
    string output = 2;
}

