syntax = "proto3";

package juki.engine.v1;

import "juki/common/v1/common.proto";

option go_package = "juki-engine/pkg/gen/juki/engine/v1";

message RouteNode {
  string id = 1;
  string name = 2; // "dashboard", "settings", or "[slug]"
  string segment = 3; // The actual URL segment
  string full_path = 4; // "/dashboard/settings"
  juki.common.v1.PageType type = 5; // STATIC, DYNAMIC, GROUP, etc.

  string page_id = 6; // Computed Page ID if this node has a page.tsx
  string layout_id = 7; // Computed Layout ID if this node has a layout.tsx
  // string loading_id = 8;
  // string error_id = 9;

  repeated RouteNode children = 10;
  juki.common.v1.Metadata meta = 11;
}
