syntax = "proto3";

package juki.common.v1;



option go_package = "juki-engine/pkg/gen/juki/common/v1";

service ThemeService {
  rpc ListThemes(ListThemesRequest) returns (ListThemesResponse);
  rpc SetTheme(SetThemeRequest) returns (SetThemeResponse);
}

message ListThemesRequest {}

message SetThemeRequest {
  string id = 1;
}

message ListThemesResponse {
  repeated Theme themes = 1;
}


message SetThemeResponse {
  Theme theme = 1;
}

message Theme {
  string id = 1;
  string name = 2;
  string description = 3;
}
